export const routes = {

    // stacks
    authStack: 'authStack',
    appStack: "appStack",

    // AuthNavigation

    // splashScreen: "splashScreen",
    // onBoarding: "onBoarding",
    welcome: "welcome",
    // pinScreen: "pinScreen",
    pinVerificationScreen: "PinVerificationScreen",
    confirmPinScreen: "confirmPinScreen",
    importWallet: "ImportWalletScreen",
    biometricPopup: "biometricPopup",
    congratulationScreen: "congratulationScreen",
    seedPhrase: "seedPhrase",
    confirmSeedPhrase: "confirmSeedPhrase",
    faceIdEnable: "faceIdEnable",
    MainTabs: "MainTabs",

    // AppNavigation
    historyScreen: "historyScreen",
    swapMain: "swapMain",
    settingScreen: "settingScreen",
    historyDetails: "historyDetails",
    rewardInfoScreen: "rewardInfoScreen",
    security: "security",
    termsOfService: "termsOfService",
    deleteAccount: "deleteAccount",
    walletConnect: "walletConnect",
    notifications: "notifications",
    importTokens: "importTokens",
    receive: "receive",
    tokenAddress: "tokenAddress",
    sendTokens: "sendTokens",
    sendTokensAddress: "sendTokensAddress",
    sendTokensAmont: "sendTokensAmont",
    sendConfirmation: "sendConfirmation",
    tokenDetails: "tokenDetails",

    // New Auth
    splashScreen: "splashScreen",
    pinScreen: "pinScreen",
    onBoarding: "onBoarding",
    createWallet: "createWallet",
    protectWallet: "protectWallet",
    importAccounts: "importAccounts",
    importPrivateKey: "importPrivateKey",
    createUserName: "createUserName",

    // New App
    homeScreen: "homeScreen",
    searchScreen: "searchScreen",
    cardTab: "cardTab",
    accountDetails: "accountDetails",
    editProfile: "editProfile",
    manageProfile: "manageProfile",
    editUserName: "editUserName",
    followersScreen: "followersScreen",
    privacyScreen: "privacyScreen",
    activities: "activities",
    activitiesDetails: "activitiesDetails",
    buyFromHome: "buyFromHome",
    buyTokenAmount: "buyTokenAmount",
    scanQrCode: "scanQrCode",
    enterSendingAmount: "enterSendingAmount",
    sendSummaryScreen: "sendSummaryScreen",
    sendSuccess: "sendSuccess",
    prepMain: "prepMain",
    addFunds: "addFunds",
    masterPerpetualFuture: "masterPerpetualFuture",
    goLong: "goLong",
    goShort: "goShort",
    adjustingLeverage: "adjustingLeverage",
    liquidation: "liquidation",
    riskTolerance: "riskTolerance",
    allSearchTokenList: "allSearchTokenList",
    addAccounts: "addAccounts",
    createAccount: "createAccount",
    watchAddress: "watchAddress",
    connectHardware: "connectHardware",
    editAccount: "editAccount",
    accountName: "accountName",
    receiveAccountAddress: "receiveAccountAddress",
    showSeedPhrase: "showSeedPhrase",
    showPrivateKey: "showPrivateKey",
    copyPrivateKey: "copyPrivateKey",
    selectAvatar: "selectAvatar",
    buyMain: "buyMain",
    tokenDetailSettings: "tokenDetailSettings",
    slippage: "slippage",
    priorityFee: "priorityFee",
    tipScreen: "tipScreen",
    youPay: "youPay",
    stakeTokensEarnAwards: "stakeTokensEarnAwards",
    enterStakeSolAmount: "enterStakeSolAmount",
    sendConfirmationScreen: "sendConfirmationScreen",
    accountSettings: "accountSettings",
    preferences: "preferences",
    preferedExplorer: "preferedExplorer",
    appIcon: "appIcon",
    preferedBitcoinAddress: "preferedBitcoinAddress",
    motionLevel: "motionLevel",
    addressBook: "addressBook",
    connectedApps: "connectedApps",
    developerSettings: "developerSettings",
    aboutPhantom: "aboutPhantom",
    displayLanguages: "displayLanguages",
    currencies: "currencies",
    securityAndPrivacy: "securityAndPrivacy",
    resetPin: "resetPin",
    requireAuthentication: "requireAuthentication",
    blockedAccounts: "blockedAccounts",
    downloadAppLogs: "downloadAppLogs",
    deleteWallet: "deleteWallet",
    resetApp: "resetApp",
    activeNetworks: "activeNetworks",
}